### PR TITLE
added person_with_disability field

### PR DESCRIPTION
**Pull request by judesamp**
added person_with_disability field, added dropdown for this field to junior stories form, added this field to seed data, adjusted controller to allow this attribute

### CODE REVIEW

**Comment by berlintam** [comment]
thanks for this @judesamp ! I'll take a look within the next week

**Comment by judesamp** [comment]
@berlintam sounds good. I wasn't sure about the placement of the dropdown in the form or the field name. Glad to make changes if needed 👍

**Comment by sareg0** [comment]
Hey @judesamp I'm helping review your pull request too! Thanks very much for your work!

Could you please also add a method called 'people_with_disability_sentence' in the 'junior_story' model, and also add it to to the index.html.erb in the junior_stories folder :)

Looks pretty good though!! Should be able to merge after those things have been added

**Comment by judesamp** [comment]
@sareg0 sure, no problem! I'll get that to you soon.

**Comment by judesamp** [comment]
okay, this is ready @sareg0! Let me know if I missed anything.

**Comment by berlintam** [comment]
thanks so much @judesamp!!!

**Pull request merged**
